// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yourname/remy/internal/agent (interfaces: Store,Embedder)
//
// Generated by this command:
//
//	mockgen -destination=mock_agent/mock_agent.go -package=mock_agent . Store,Embedder
//

// Package mock_agent is a generated GoMock package.
package mock_agent

import (
	context "context"
	reflect "reflect"

	memory "github.com/yourname/remy/internal/memory"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetMessage mocks base method.
func (m *MockStore) GetMessage(ctx context.Context, id string) (*memory.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, id)
	ret0, _ := ret[0].(*memory.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockStoreMockRecorder) GetMessage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockStore)(nil).GetMessage), ctx, id)
}

// GetMessages mocks base method.
func (m *MockStore) GetMessages(ctx context.Context, limit, offset int) ([]memory.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, limit, offset)
	ret0, _ := ret[0].([]memory.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockStoreMockRecorder) GetMessages(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockStore)(nil).GetMessages), ctx, limit, offset)
}

// GetMessagesBySession mocks base method.
func (m *MockStore) GetMessagesBySession(ctx context.Context, sessionID string) ([]memory.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBySession", ctx, sessionID)
	ret0, _ := ret[0].([]memory.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBySession indicates an expected call of GetMessagesBySession.
func (mr *MockStoreMockRecorder) GetMessagesBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBySession", reflect.TypeOf((*MockStore)(nil).GetMessagesBySession), ctx, sessionID)
}

// GetScratchpad mocks base method.
func (m *MockStore) GetScratchpad(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScratchpad", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScratchpad indicates an expected call of GetScratchpad.
func (mr *MockStoreMockRecorder) GetScratchpad(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScratchpad", reflect.TypeOf((*MockStore)(nil).GetScratchpad), ctx)
}

// LogActivity mocks base method.
func (m *MockStore) LogActivity(ctx context.Context, entry *memory.ActivityEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogActivity", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogActivity indicates an expected call of LogActivity.
func (mr *MockStoreMockRecorder) LogActivity(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogActivity", reflect.TypeOf((*MockStore)(nil).LogActivity), ctx, entry)
}

// SaveMessage mocks base method.
func (m *MockStore) SaveMessage(ctx context.Context, msg *memory.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockStoreMockRecorder) SaveMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockStore)(nil).SaveMessage), ctx, msg)
}

// SaveMessageVector mocks base method.
func (m *MockStore) SaveMessageVector(ctx context.Context, messageID string, embedding []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessageVector", ctx, messageID, embedding)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessageVector indicates an expected call of SaveMessageVector.
func (mr *MockStoreMockRecorder) SaveMessageVector(ctx, messageID, embedding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessageVector", reflect.TypeOf((*MockStore)(nil).SaveMessageVector), ctx, messageID, embedding)
}

// SearchEpisodes mocks base method.
func (m *MockStore) SearchEpisodes(ctx context.Context, embedding []byte, limit int) ([]memory.Episode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchEpisodes", ctx, embedding, limit)
	ret0, _ := ret[0].([]memory.Episode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchEpisodes indicates an expected call of SearchEpisodes.
func (mr *MockStoreMockRecorder) SearchEpisodes(ctx, embedding, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchEpisodes", reflect.TypeOf((*MockStore)(nil).SearchEpisodes), ctx, embedding, limit)
}

// SearchFacts mocks base method.
func (m *MockStore) SearchFacts(ctx context.Context, embedding []byte, limit int) ([]memory.Fact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFacts", ctx, embedding, limit)
	ret0, _ := ret[0].([]memory.Fact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFacts indicates an expected call of SearchFacts.
func (mr *MockStoreMockRecorder) SearchFacts(ctx, embedding, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFacts", reflect.TypeOf((*MockStore)(nil).SearchFacts), ctx, embedding, limit)
}

// UpdateScratchpad mocks base method.
func (m *MockStore) UpdateScratchpad(ctx context.Context, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScratchpad", ctx, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScratchpad indicates an expected call of UpdateScratchpad.
func (mr *MockStoreMockRecorder) UpdateScratchpad(ctx, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScratchpad", reflect.TypeOf((*MockStore)(nil).UpdateScratchpad), ctx, content)
}

// MockEmbedder is a mock of Embedder interface.
type MockEmbedder struct {
	ctrl     *gomock.Controller
	recorder *MockEmbedderMockRecorder
	isgomock struct{}
}

// MockEmbedderMockRecorder is the mock recorder for MockEmbedder.
type MockEmbedderMockRecorder struct {
	mock *MockEmbedder
}

// NewMockEmbedder creates a new mock instance.
func NewMockEmbedder(ctrl *gomock.Controller) *MockEmbedder {
	mock := &MockEmbedder{ctrl: ctrl}
	mock.recorder = &MockEmbedderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbedder) EXPECT() *MockEmbedderMockRecorder {
	return m.recorder
}

// GenerateEmbedding mocks base method.
func (m *MockEmbedder) GenerateEmbedding(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateEmbedding", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateEmbedding indicates an expected call of GenerateEmbedding.
func (mr *MockEmbedderMockRecorder) GenerateEmbedding(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateEmbedding", reflect.TypeOf((*MockEmbedder)(nil).GenerateEmbedding), ctx, text)
}
