// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/danmurf/remy/internal/agent (interfaces: Store,Embedder,PersonaLoader)
//
// Generated by this command:
//
//	mockgen -destination=mock_agent/mock_agent.go -package=mock_agent . Store,Embedder,PersonaLoader
//

// Package mock_agent is a generated GoMock package.
package mock_agent

import (
	context "context"
	reflect "reflect"

	memory "github.com/danmurf/remy/internal/memory"
	persona "github.com/danmurf/remy/internal/persona"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetEntities mocks base method.
func (m *MockStore) GetEntities(ctx context.Context) ([]memory.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntities", ctx)
	ret0, _ := ret[0].([]memory.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntities indicates an expected call of GetEntities.
func (mr *MockStoreMockRecorder) GetEntities(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntities", reflect.TypeOf((*MockStore)(nil).GetEntities), ctx)
}

// GetEpisodes mocks base method.
func (m *MockStore) GetEpisodes(ctx context.Context, limit, offset int) ([]memory.Episode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpisodes", ctx, limit, offset)
	ret0, _ := ret[0].([]memory.Episode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpisodes indicates an expected call of GetEpisodes.
func (mr *MockStoreMockRecorder) GetEpisodes(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpisodes", reflect.TypeOf((*MockStore)(nil).GetEpisodes), ctx, limit, offset)
}

// GetEpisodesByTimeRange mocks base method.
func (m *MockStore) GetEpisodesByTimeRange(ctx context.Context, start, end int64) ([]memory.Episode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEpisodesByTimeRange", ctx, start, end)
	ret0, _ := ret[0].([]memory.Episode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEpisodesByTimeRange indicates an expected call of GetEpisodesByTimeRange.
func (mr *MockStoreMockRecorder) GetEpisodesByTimeRange(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEpisodesByTimeRange", reflect.TypeOf((*MockStore)(nil).GetEpisodesByTimeRange), ctx, start, end)
}

// GetFacts mocks base method.
func (m *MockStore) GetFacts(ctx context.Context, limit, offset int) ([]memory.Fact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFacts", ctx, limit, offset)
	ret0, _ := ret[0].([]memory.Fact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFacts indicates an expected call of GetFacts.
func (mr *MockStoreMockRecorder) GetFacts(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFacts", reflect.TypeOf((*MockStore)(nil).GetFacts), ctx, limit, offset)
}

// GetMessage mocks base method.
func (m *MockStore) GetMessage(ctx context.Context, id string) (*memory.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, id)
	ret0, _ := ret[0].(*memory.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockStoreMockRecorder) GetMessage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockStore)(nil).GetMessage), ctx, id)
}

// GetMessages mocks base method.
func (m *MockStore) GetMessages(ctx context.Context, limit, offset int) ([]memory.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, limit, offset)
	ret0, _ := ret[0].([]memory.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockStoreMockRecorder) GetMessages(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockStore)(nil).GetMessages), ctx, limit, offset)
}

// GetMessagesBySession mocks base method.
func (m *MockStore) GetMessagesBySession(ctx context.Context, sessionID string) ([]memory.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBySession", ctx, sessionID)
	ret0, _ := ret[0].([]memory.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBySession indicates an expected call of GetMessagesBySession.
func (mr *MockStoreMockRecorder) GetMessagesBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBySession", reflect.TypeOf((*MockStore)(nil).GetMessagesBySession), ctx, sessionID)
}

// GetRelationships mocks base method.
func (m *MockStore) GetRelationships(ctx context.Context) ([]memory.Relationship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelationships", ctx)
	ret0, _ := ret[0].([]memory.Relationship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelationships indicates an expected call of GetRelationships.
func (mr *MockStoreMockRecorder) GetRelationships(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelationships", reflect.TypeOf((*MockStore)(nil).GetRelationships), ctx)
}

// GetScratchpad mocks base method.
func (m *MockStore) GetScratchpad(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScratchpad", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScratchpad indicates an expected call of GetScratchpad.
func (mr *MockStoreMockRecorder) GetScratchpad(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScratchpad", reflect.TypeOf((*MockStore)(nil).GetScratchpad), ctx)
}

// LogActivity mocks base method.
func (m *MockStore) LogActivity(ctx context.Context, entry *memory.ActivityEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogActivity", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogActivity indicates an expected call of LogActivity.
func (mr *MockStoreMockRecorder) LogActivity(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogActivity", reflect.TypeOf((*MockStore)(nil).LogActivity), ctx, entry)
}

// SaveEntity mocks base method.
func (m *MockStore) SaveEntity(ctx context.Context, entity memory.Entity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEntity", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEntity indicates an expected call of SaveEntity.
func (mr *MockStoreMockRecorder) SaveEntity(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEntity", reflect.TypeOf((*MockStore)(nil).SaveEntity), ctx, entity)
}

// SaveEpisode mocks base method.
func (m *MockStore) SaveEpisode(ctx context.Context, ep *memory.Episode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEpisode", ctx, ep)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEpisode indicates an expected call of SaveEpisode.
func (mr *MockStoreMockRecorder) SaveEpisode(ctx, ep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEpisode", reflect.TypeOf((*MockStore)(nil).SaveEpisode), ctx, ep)
}

// SaveEpisodeVector mocks base method.
func (m *MockStore) SaveEpisodeVector(ctx context.Context, episodeID string, embedding []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEpisodeVector", ctx, episodeID, embedding)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEpisodeVector indicates an expected call of SaveEpisodeVector.
func (mr *MockStoreMockRecorder) SaveEpisodeVector(ctx, episodeID, embedding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEpisodeVector", reflect.TypeOf((*MockStore)(nil).SaveEpisodeVector), ctx, episodeID, embedding)
}

// SaveFact mocks base method.
func (m *MockStore) SaveFact(ctx context.Context, fact *memory.Fact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFact", ctx, fact)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFact indicates an expected call of SaveFact.
func (mr *MockStoreMockRecorder) SaveFact(ctx, fact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFact", reflect.TypeOf((*MockStore)(nil).SaveFact), ctx, fact)
}

// SaveFactVector mocks base method.
func (m *MockStore) SaveFactVector(ctx context.Context, factID string, embedding []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFactVector", ctx, factID, embedding)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFactVector indicates an expected call of SaveFactVector.
func (mr *MockStoreMockRecorder) SaveFactVector(ctx, factID, embedding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFactVector", reflect.TypeOf((*MockStore)(nil).SaveFactVector), ctx, factID, embedding)
}

// SaveMessage mocks base method.
func (m *MockStore) SaveMessage(ctx context.Context, msg *memory.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockStoreMockRecorder) SaveMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockStore)(nil).SaveMessage), ctx, msg)
}

// SaveMessageVector mocks base method.
func (m *MockStore) SaveMessageVector(ctx context.Context, messageID string, embedding []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessageVector", ctx, messageID, embedding)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessageVector indicates an expected call of SaveMessageVector.
func (mr *MockStoreMockRecorder) SaveMessageVector(ctx, messageID, embedding any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessageVector", reflect.TypeOf((*MockStore)(nil).SaveMessageVector), ctx, messageID, embedding)
}

// SaveRelationship mocks base method.
func (m *MockStore) SaveRelationship(ctx context.Context, rel *memory.Relationship) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRelationship", ctx, rel)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRelationship indicates an expected call of SaveRelationship.
func (mr *MockStoreMockRecorder) SaveRelationship(ctx, rel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRelationship", reflect.TypeOf((*MockStore)(nil).SaveRelationship), ctx, rel)
}

// SearchEpisodes mocks base method.
func (m *MockStore) SearchEpisodes(ctx context.Context, embedding []byte, limit int) ([]memory.Episode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchEpisodes", ctx, embedding, limit)
	ret0, _ := ret[0].([]memory.Episode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchEpisodes indicates an expected call of SearchEpisodes.
func (mr *MockStoreMockRecorder) SearchEpisodes(ctx, embedding, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchEpisodes", reflect.TypeOf((*MockStore)(nil).SearchEpisodes), ctx, embedding, limit)
}

// SearchFacts mocks base method.
func (m *MockStore) SearchFacts(ctx context.Context, embedding []byte, limit int) ([]memory.Fact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchFacts", ctx, embedding, limit)
	ret0, _ := ret[0].([]memory.Fact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchFacts indicates an expected call of SearchFacts.
func (mr *MockStoreMockRecorder) SearchFacts(ctx, embedding, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchFacts", reflect.TypeOf((*MockStore)(nil).SearchFacts), ctx, embedding, limit)
}

// UpdateFact mocks base method.
func (m *MockStore) UpdateFact(ctx context.Context, fact *memory.Fact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFact", ctx, fact)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFact indicates an expected call of UpdateFact.
func (mr *MockStoreMockRecorder) UpdateFact(ctx, fact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFact", reflect.TypeOf((*MockStore)(nil).UpdateFact), ctx, fact)
}

// UpdateScratchpad mocks base method.
func (m *MockStore) UpdateScratchpad(ctx context.Context, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScratchpad", ctx, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScratchpad indicates an expected call of UpdateScratchpad.
func (mr *MockStoreMockRecorder) UpdateScratchpad(ctx, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScratchpad", reflect.TypeOf((*MockStore)(nil).UpdateScratchpad), ctx, content)
}

// MockEmbedder is a mock of Embedder interface.
type MockEmbedder struct {
	ctrl     *gomock.Controller
	recorder *MockEmbedderMockRecorder
	isgomock struct{}
}

// MockEmbedderMockRecorder is the mock recorder for MockEmbedder.
type MockEmbedderMockRecorder struct {
	mock *MockEmbedder
}

// NewMockEmbedder creates a new mock instance.
func NewMockEmbedder(ctrl *gomock.Controller) *MockEmbedder {
	mock := &MockEmbedder{ctrl: ctrl}
	mock.recorder = &MockEmbedderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbedder) EXPECT() *MockEmbedderMockRecorder {
	return m.recorder
}

// GenerateEmbedding mocks base method.
func (m *MockEmbedder) GenerateEmbedding(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateEmbedding", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateEmbedding indicates an expected call of GenerateEmbedding.
func (mr *MockEmbedderMockRecorder) GenerateEmbedding(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateEmbedding", reflect.TypeOf((*MockEmbedder)(nil).GenerateEmbedding), ctx, text)
}

// MockPersonaLoader is a mock of PersonaLoader interface.
type MockPersonaLoader struct {
	ctrl     *gomock.Controller
	recorder *MockPersonaLoaderMockRecorder
	isgomock struct{}
}

// MockPersonaLoaderMockRecorder is the mock recorder for MockPersonaLoader.
type MockPersonaLoaderMockRecorder struct {
	mock *MockPersonaLoader
}

// NewMockPersonaLoader creates a new mock instance.
func NewMockPersonaLoader(ctrl *gomock.Controller) *MockPersonaLoader {
	mock := &MockPersonaLoader{ctrl: ctrl}
	mock.recorder = &MockPersonaLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonaLoader) EXPECT() *MockPersonaLoaderMockRecorder {
	return m.recorder
}

// ListPersonas mocks base method.
func (m *MockPersonaLoader) ListPersonas(dir, activeName string) ([]persona.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPersonas", dir, activeName)
	ret0, _ := ret[0].([]persona.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPersonas indicates an expected call of ListPersonas.
func (mr *MockPersonaLoaderMockRecorder) ListPersonas(dir, activeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPersonas", reflect.TypeOf((*MockPersonaLoader)(nil).ListPersonas), dir, activeName)
}

// LoadPersona mocks base method.
func (m *MockPersonaLoader) LoadPersona(path string) (*persona.Persona, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPersona", path)
	ret0, _ := ret[0].(*persona.Persona)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPersona indicates an expected call of LoadPersona.
func (mr *MockPersonaLoaderMockRecorder) LoadPersona(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPersona", reflect.TypeOf((*MockPersonaLoader)(nil).LoadPersona), path)
}
