DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS activity_log;
DROP TABLE IF EXISTS scratchpad;
DROP TABLE IF EXISTS relationships;
DROP TABLE IF EXISTS entities;
DROP TABLE IF EXISTS facts;
DROP TABLE IF EXISTS episodes;
DROP TABLE IF EXISTS messages;
