// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yourname/remy/internal/llm (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -destination=mock_llm/mock_llm.go -package=mock_llm . Provider
//

// Package mock_llm is a generated GoMock package.
package mock_llm

import (
	context "context"
	reflect "reflect"

	llm "github.com/yourname/remy/internal/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockProvider) Chat(ctx context.Context, req llm.ChatRequest) (*llm.ChatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, req)
	ret0, _ := ret[0].(*llm.ChatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockProviderMockRecorder) Chat(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockProvider)(nil).Chat), ctx, req)
}

// ChatStream mocks base method.
func (m *MockProvider) ChatStream(ctx context.Context, req llm.ChatRequest) (<-chan llm.StreamChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", ctx, req)
	ret0, _ := ret[0].(<-chan llm.StreamChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockProviderMockRecorder) ChatStream(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockProvider)(nil).ChatStream), ctx, req)
}

// Embed mocks base method.
func (m *MockProvider) Embed(ctx context.Context, text string) ([]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embed", ctx, text)
	ret0, _ := ret[0].([]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Embed indicates an expected call of Embed.
func (mr *MockProviderMockRecorder) Embed(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embed", reflect.TypeOf((*MockProvider)(nil).Embed), ctx, text)
}
