// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/danmurf/remy/internal/scheduler (interfaces: Store,Agent)
//
// Generated by this command:
//
//	mockgen -destination=mock_scheduler/mock_scheduler.go -package=mock_scheduler . Store,Agent
//

// Package mock_scheduler is a generated GoMock package.
package mock_scheduler

import (
	context "context"
	reflect "reflect"

	memory "github.com/danmurf/remy/internal/memory"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CancelTask mocks base method.
func (m *MockStore) CancelTask(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelTask indicates an expected call of CancelTask.
func (mr *MockStoreMockRecorder) CancelTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTask", reflect.TypeOf((*MockStore)(nil).CancelTask), ctx, id)
}

// GetDueTasks mocks base method.
func (m *MockStore) GetDueTasks(ctx context.Context, now int64) ([]memory.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDueTasks", ctx, now)
	ret0, _ := ret[0].([]memory.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDueTasks indicates an expected call of GetDueTasks.
func (mr *MockStoreMockRecorder) GetDueTasks(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDueTasks", reflect.TypeOf((*MockStore)(nil).GetDueTasks), ctx, now)
}

// GetTask mocks base method.
func (m *MockStore) GetTask(ctx context.Context, id string) (*memory.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, id)
	ret0, _ := ret[0].(*memory.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockStoreMockRecorder) GetTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockStore)(nil).GetTask), ctx, id)
}

// GetTasks mocks base method.
func (m *MockStore) GetTasks(ctx context.Context, status string) ([]memory.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx, status)
	ret0, _ := ret[0].([]memory.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockStoreMockRecorder) GetTasks(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockStore)(nil).GetTasks), ctx, status)
}

// SaveTask mocks base method.
func (m *MockStore) SaveTask(ctx context.Context, task *memory.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTask indicates an expected call of SaveTask.
func (mr *MockStoreMockRecorder) SaveTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTask", reflect.TypeOf((*MockStore)(nil).SaveTask), ctx, task)
}

// UpdateTaskStatus mocks base method.
func (m *MockStore) UpdateTaskStatus(ctx context.Context, id, status string, firedAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", ctx, id, status, firedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockStoreMockRecorder) UpdateTaskStatus(ctx, id, status, firedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockStore)(nil).UpdateTaskStatus), ctx, id, status, firedAt)
}

// MockAgent is a mock of Agent interface.
type MockAgent struct {
	ctrl     *gomock.Controller
	recorder *MockAgentMockRecorder
	isgomock struct{}
}

// MockAgentMockRecorder is the mock recorder for MockAgent.
type MockAgentMockRecorder struct {
	mock *MockAgent
}

// NewMockAgent creates a new mock instance.
func NewMockAgent(ctrl *gomock.Controller) *MockAgent {
	mock := &MockAgent{ctrl: ctrl}
	mock.recorder = &MockAgentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgent) EXPECT() *MockAgentMockRecorder {
	return m.recorder
}

// HandleMessage mocks base method.
func (m *MockAgent) HandleMessage(ctx context.Context, userMsg string) (*memory.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMessage", ctx, userMsg)
	ret0, _ := ret[0].(*memory.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleMessage indicates an expected call of HandleMessage.
func (mr *MockAgentMockRecorder) HandleMessage(ctx, userMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMessage", reflect.TypeOf((*MockAgent)(nil).HandleMessage), ctx, userMsg)
}
